name: test

on: [pull_request]

jobs:
  sorry:
    name: sorry

    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    strategy:
     fail-fast: false
     matrix:
       runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

    steps:
      - name: test
        run: ./xxx
